name: GitHub Atmos Deployment Demo
run-name: A demo deployment action for atmos workflows 👽
on:
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: plat-ue2-dev-dynamodb
          - environment: plat-ue2-stage-dynamodb
          - environment: plat-ue2-prod-dynamodb
    environment:
      name: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "atmos terraform apply dynamodb -s demo-plat-ue2-dev"
