name: GitHub Atmos Deployment Demo
run-name: A demo deployment action for atmos workflows 👽
on:
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          environment: plat-ue2-dev-dynamodb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
