name: GitHub Atmos Deployment Demo
run-name: A demo deployment action for atmos workflows 👽
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo version_matrix="$(jq -n --arg v plat-ue2-dev-dynamodb '[{environment: $v}]')" >> $GITHUB_OUTPUT
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}
  deploy:
    name: deploy
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dynamodb:
              - 'components/terraform/dynamodb/**'
            s3bucket:
              - 'components/terraform/s3bucket/**'
            sqsQueue:
              - 'components/terraform/sqsQueue/**'
            devStack:
              - 'stacks/orgs/demo/plat/dev/**'
            prodStack:
              - 'stacks/orgs/demo/plat/prod/**'
            stageStack:
              - 'stacks/orgs/demo/plat/stage/**'

      - run: echo "atmos terraform apply dynamodb -s demo-plat-ue2-dev"
