name: GitHub Atmos Deployment Demo
run-name: A demo deployment action for atmos workflows 👽
on:
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: plat-ue2-dev-dynamodb deployment
        id: create_deployment_dev
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          owner: ${{ github.repo }}
          repo: ${{ github.repo }}
          ref: gitub.sha
          environment: plat-ue2-dev-dynamodb
          auto_merge: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
